=== divyank01/Blow_v1/BlowORM/bin/com/sales/xmls/BlowConf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  *  BLOW-ORM is an open source ORM for java and its currently under development.
  *
  *  Copyright (C) 2016  @author Divyank Sharma
  *
  *  This program is free software: you can redistribute it and/or modify
  *  it under the terms of the GNU General Public License as published by
  *  the Free Software Foundation, either version 3 of the License, or
  *  (at your option) any later version.
  *
  *  This program is distributed in the hope that it will be useful,
  *  but WITHOUT ANY WARRANTY; without even the implied warranty of
  *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  *  GNU General Public License for more details.
  *
  *  You should have received a copy of the GNU General Public License
  *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
  *  
  *  
  *  In Addition to it if you find any bugs or encounter any issue you need to notify me.
  *  I appreciate any suggestions to improve it.
  *  @mailto: divyank01@gmail.com-->
  
<ns:schema targetNamespace="http://www.BlowORM.org/BlowConf" elementFormDefault="qualified" xmlns:ns="http://www.w3.org/2001/XMLSchema" xmlns="http://www.BlowORM.org/BlowConf">

	<ns:complexType name="JDBCConnection">
		<ns:sequence>
			<ns:element name="URL" type="URL" minOccurs="1" maxOccurs="1" nillable="false">
			</ns:element>
			<ns:element name="PASSWORD" type="PASSWORD" minOccurs="1" maxOccurs="1" nillable="false">
			</ns:element>
			<ns:element name="USER" type="USER" minOccurs="1" maxOccurs="1" nillable="false">
			</ns:element>
			<ns:element name="JDBCDriver" type="ns:string" maxOccurs="1" minOccurs="1">
			</ns:element>
			<ns:element name="QUERIES" type="QUERIES" maxOccurs="1" minOccurs="0">
			</ns:element>
			<ns:element name="MAPPINGS" type="MAPPINGS" minOccurs="0" maxOccurs="unbounded">
			</ns:element>
			<ns:element name="ANNOTATIONS" type="ANNOTIONS" maxOccurs="1" minOccurs="0">
			</ns:element>
			<ns:element name="Schema" type="ns:string" maxOccurs="1" minOccurs="1">
				<ns:annotation>
					<ns:documentation>
						multiple schema can be mentioned for loading
						tables separated by comma.
					</ns:documentation>
				</ns:annotation>
			</ns:element>
			<ns:element name="GenerateSchema" type="ns:boolean" maxOccurs="1" minOccurs="1">
			</ns:element>
			<ns:element name="SqlLogging" type="ns:boolean" maxOccurs="1" minOccurs="1"></ns:element>
		</ns:sequence>
	</ns:complexType>

	<ns:simpleType name="URL">
		<ns:restriction base="ns:string"></ns:restriction>
	</ns:simpleType>

	<ns:simpleType name="USER">
		<ns:restriction base="ns:string"></ns:restriction>
	</ns:simpleType>

	<ns:simpleType name="PASSWORD">
		<ns:restriction base="ns:string"></ns:restriction>
	</ns:simpleType>

	<ns:element name="JDBCConnection" type="JDBCConnection"></ns:element>

	<ns:complexType name="MAPPINGS">
		<ns:attribute name="file" use="required">
			<ns:simpleType>
				<ns:restriction base="ns:string">
					<ns:pattern value=".*.blow.xml"></ns:pattern>
				</ns:restriction>
			</ns:simpleType>
		</ns:attribute>

	</ns:complexType>

	<ns:complexType name="QUERY">
		<ns:attribute name="file" use="required">
			<ns:simpleType>
				<ns:restriction base="ns:string">
					<ns:pattern value=".*.blow.query.xml"></ns:pattern>
				</ns:restriction>
			</ns:simpleType>
		</ns:attribute>
	</ns:complexType>
	
	<ns:complexType name="ANNOTIONS">
		<ns:sequence>
			<ns:element name="package-scan" maxOccurs="unbounded" minOccurs="1">
				<ns:simpleType>
					<ns:restriction base="ns:string">
						<ns:whiteSpace value="collapse"></ns:whiteSpace>
					</ns:restriction>
				</ns:simpleType>
			</ns:element>
		</ns:sequence>
		<ns:attribute name="use" type="ns:boolean" use="required"></ns:attribute>
	</ns:complexType>

	<ns:simpleType name="DATABASE">
		<ns:restriction base="ns:string">
			<ns:enumeration value="oracle"></ns:enumeration>
			<ns:enumeration value="mysql"></ns:enumeration>
		</ns:restriction></ns:simpleType>

	<ns:complexType name="QUERIES">
		<ns:sequence>
			<ns:element name="Query" type="QUERY" minOccurs="1" maxOccurs="unbounded"></ns:element>
		</ns:sequence>
	</ns:complexType>
</ns:schema>

=== divyank01/Blow_v1/BlowTest/src/BLOW-ORM-CONFIG.xml
<?xml version="1.0" encoding="UTF-8"?>
<JDBCConnection xmlns="http://www.BlowORM.org/BlowConf"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.BlowORM.org/BlowConf ../../BlowORM/src/com/sales/xmls/BlowConf.xsd">

	<!-- basic configs -->
	<URL>jdbc:oracle:thin:@localhost:1521:xe</URL>
	<PASSWORD>divyank99</PASSWORD>
	<USER>divyank</USER>
	<!-- Oracle10g driver class -->
	 <JDBCDriver>oracle.jdbc.driver.OracleDriver</JDBCDriver>
	
	<!-- Oracle11g driver class -->
	<!-- <JDBCDriver>oracle.jdbc.OracleDriver</JDBCDriver> -->
	
	<QUERIES>
		<Query file="com/sales/xmls/some.blow.query.xml"/>
		<Query file="com/sales/xmls/some.blow.query.xml"/>
	</QUERIES>

	<!-- mappings -->
	<MAPPINGS file="com/sales/xmls/first.blow.xml" />
	<MAPPINGS file="com/sales/xmls/second.blow.xml" />
	<!-- <MAPPINGS file="com/sales/xmls/three.blow.xml"/> -->
	
	<!-- config annotation -->
	<ANNOTATIONS use="true">
		<package-scan>com.sales.pojo</package-scan>
		<package-scan>com.customer.pojo</package-scan>
	</ANNOTATIONS>

	<!-- multiple schema can be mentioned for loading tables separated by comma -->
	<Schema>DIVYANK</Schema>
	<!-- generate schema -->
	<GenerateSchema>true</GenerateSchema>
	<SqlLogging>true</SqlLogging>
</JDBCConnection>
