=== divyank01/Blow_v1/BlowORM/bin/com/sales/xmls/Mapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.blow.org/Mapping"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:MAP="http://www.blow.org/Mapping">

	<complexType name="Mapping">
		<sequence>
			<element name="Class" type="string" minOccurs="1" maxOccurs="1"></element>
			<element name="RDBSchema" type="string" minOccurs="1"
				maxOccurs="1"></element>
			<element name="Map" type="MAP:Map" minOccurs="1" maxOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="Map">
        <sequence>
			<element name="Property" type="MAP:Property" minOccurs="0" maxOccurs="unbounded">
			</element>
			<element name="one-2-one" type="MAP:one-2-one" maxOccurs="unbounded" minOccurs="0">
			</element>
			<element name="one-2-many" type="MAP:one-2-many" maxOccurs="unbounded" minOccurs="0">
			</element>
			<element name="complexPrimaryKey" type="MAP:ComplexPrimaryKey" maxOccurs="unbounded" minOccurs="0"></element>
		</sequence>
	</complexType>

	<complexType name="Mappings">
		<sequence>
			<element name="Mapping" type="MAP:Mapping" minOccurs="1"
				maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<element name="Mappings" type="MAP:Mappings"></element>

	<complexType name="Property">
		<attribute name="type" type="string" use="required"></attribute>
		<attribute name="colName" type="string" use="required"></attribute>
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="primary-key" type="boolean"></attribute>
	</complexType>

	<complexType name="one-2-one">
        <annotation>
        	<documentation>this attribute can handle one to one as well as many to one relationships.</documentation>
        </annotation>
        <attribute name="name" type="string" use="required"></attribute>
		<attribute name="ref-class" type="string" use="required"></attribute>
		<attribute name="foreign-key" type="string" use="required"></attribute>
	</complexType>

	<complexType name="one-2-many">
        <annotation>
        	<documentation>this attribute can handle one to many relationship.</documentation>
        </annotation>
        <attribute name="ref-class" type="string" use="required"></attribute>
		<attribute name="foreign-key" type="string" use="required"></attribute>
		<attribute name="collectionType" use="required">
			<simpleType>
				<restriction base="string">
					<enumeration value="list"></enumeration>
					<enumeration value="set"></enumeration>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="name" type="string" use="required"></attribute>
	</complexType>

	<complexType name="ComplexPrimaryKey">
		<sequence>
			<element name="property" type="MAP:Property" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>
</schema>

=== divyank01/Blow_v1/BlowTest/bin/com/sales/xmls/first.blow.xml
<?xml version="1.0" encoding="UTF-8"?>
<MAP:Mappings xmlns:MAP="http://www.blow.org/Mapping" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.blow.org/Mapping ../../../../../BlowORM/src/com/sales/xmls/Mapping.xsd ">
  <MAP:Mapping>
    <MAP:Class>com.sales.pojo.Prodcty</MAP:Class>
    <MAP:RDBSchema>product</MAP:RDBSchema>
    <MAP:Map>
    	<MAP:Property name="id" type="int" colName="id" primary-key="true" length="5" generated="true" seq="product_seq"/>
    	<MAP:Property name="name" type="String" colName="name" length="50"/>
    	<MAP:Property name="catId" type="long" colName="cat_id"/> 	
    	<MAP:one-2-one name="details" ref-class="com.sales.pojo.ProductDetails" foreign-key="PROD_ID" foreign-key-ref="true"/>
    	<MAP:one-2-one name="stock" ref-class="com.sales.pojo.Stock" foreign-key="PROD_ID" foreign-key-ref="true"/>
    	<MAP:one-2-one name="epd" ref-class="com.sales.pojo.ElectronicProductDetails" foreign-key="PROD_ID" foreign-key-ref="true"/>
    	<MAP:one-2-many ref-class="com.sales.pojo.Stock" name="stocks" foreign-key="PROD_ID" collectionType="list" foreign-key-ref="true"/>
    </MAP:Map>
  </MAP:Mapping>
  
  <MAP:Mapping>
  	<MAP:Class>com.sales.pojo.ProductDetails</MAP:Class>
  	<MAP:RDBSchema>product_details</MAP:RDBSchema>
  	<MAP:Map>
     	<MAP:Property name="id" type="int" colName="id" primary-key="true" generated="true" seq="PD_SEQ"/>
  		<MAP:Property name="prodId" type="int" colName="PROD_ID"/>
  		<MAP:Property name="brand" type="String" colName="BRAND"/>
  		<MAP:Property name="color" type="String" colName="COLOR"/>
  		<MAP:Property name="productSize" type="String" colName="PROD_SIZE"/>
  		<MAP:Property name="price" type="int" colName="PRICE"/>
  		<MAP:Property name="material" type="String" colName="MATERIAL"/>
  		<MAP:one-2-one name="product" ref-class="com.sales.pojo.Prodcty" foreign-key="PROD_ID"/>
  	</MAP:Map>
  </MAP:Mapping>
  <MAP:Mapping>
  	<MAP:Class>com.sales.pojo.ElectronicProductDetails</MAP:Class>
  	<MAP:RDBSchema>ELECTRONIC_PRODUCT_DETAILS</MAP:RDBSchema>
  	<MAP:Map>
     	<MAP:Property name="id" type="int" colName="id" primary-key="true" generated="true" seq="EPD_SEQ"/>
  		<MAP:Property name="description" type="String" colName="ELE_DESCRIPTION"/>
  		<MAP:Property name="techDetails" type="String" colName="TECH_DETAILS"/>
  		<MAP:Property name="prodId" type="int" colName="PROD_ID"/>
  		<MAP:Property name="brand" type="String" colName="BRAND"/>
  		<MAP:Property name="color" type="String" colName="COLOR"/>
  		<MAP:Property name="price" type="int" colName="PRICE"/>
  		<MAP:Property name="material" type="String" colName="MATERIAL"/>
  		<MAP:one-2-one name="product" ref-class="com.sales.pojo.Prodcty" foreign-key="ID"/>
  	</MAP:Map>
  </MAP:Mapping>
  
  <MAP:Mapping>
  	<MAP:Class>com.sales.pojos.ElectronicProductDetails</MAP:Class>
  	<MAP:RDBSchema>ELECTRONIC_PRODUCT_DETAILS</MAP:RDBSchema>
  	<MAP:Map>
     	<MAP:Property name="id" type="int" colName="id" primary-key="true" generated="true" seq="EPD_SEQ"/>
  		<MAP:Property name="description" type="String" colName="ELE_DESCRIPTION"/>
  		<MAP:Property name="techDetails" type="String" colName="TECH_DETAILS"/>
  		<MAP:Property name="prodId" type="int" colName="PROD_ID"/>
  		<MAP:Property name="brand" type="String" colName="BRAND"/>
  		<MAP:Property name="color" type="String" colName="COLOR"/>
  		<MAP:Property name="price" type="int" colName="PRICE"/>
  		<MAP:Property name="material" type="String" colName="MATERIAL"/>
  		<MAP:one-2-one name="product" ref-class="com.sales.pojo.Prodcty" foreign-key="ID"/>
  	</MAP:Map>
  </MAP:Mapping>
</MAP:Mappings>

=== divyank01/Blow_v1/BlowTest/src/com/sales/xmls/second.blow.xml
<?xml version="1.0" encoding="UTF-8"?>
<MAP:Mappings xmlns:MAP="http://www.blow.org/Mapping" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.blow.org/Mapping ../../../../../BlowORM/src/com/sales/xmls/Mapping.xsd ">
  <MAP:Mapping>
    <MAP:Class>com.sales.pojo.Stock</MAP:Class>
    <MAP:RDBSchema>STOCK</MAP:RDBSchema>
    <MAP:Map>
    	<MAP:Property name="id" type="int" colName="id" primary-key="true"/>
    	<MAP:Property name="productId" type="int" colName="prod_id"/>
    	<MAP:Property name="liveStockCount" type="double" colName="live_stock"/>
    	<MAP:Property name="locId" type="int" colName="loc_id"/>
    	<MAP:one-2-one name="product" ref-class="com.sales.pojo.Prodcty" foreign-key="PROD_ID"/>
    	<MAP:one-2-one name="mappings" ref-class="com.sales.pojo.StockMappings" foreign-key="ID"/>
    </MAP:Map>
  </MAP:Mapping>
  <MAP:Mapping>
    <MAP:Class>com.sales.pojo.StockMappings</MAP:Class>
    <MAP:RDBSchema>STOCK_MAPPINGS</MAP:RDBSchema>
    <MAP:Map>
    	<MAP:Property name="id" type="int" colName="id" primary-key="true"/>
    	<MAP:Property name="generatedProductId" type="double" colName="GEN_PROD_ID"/>
    	<MAP:Property name="stockId" type="int" colName="STOCK_ID"/>
    	<MAP:Property name="locId" type="int" colName="loc_id"/>
    	<MAP:one-2-one name="stock" ref-class="com.sales.pojo.Stock" foreign-key="STOCK_ID"/>
    </MAP:Map>
  </MAP:Mapping>
</MAP:Mappings>

=== divyank01/Blow_v1/BlowTest/src/com/sales/xmls/three.blow.xml
<?xml version="1.0" encoding="UTF-8"?>
<MAP:Mappings xmlns:MAP="http://www.blow.org/Mapping" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.blow.org/Mapping ../../../../../BlowORM/src/com/sales/xmls/Mapping.xsd ">
 <MAP:Mapping>
    <MAP:Class>com.sales.pojo.Prodcty</MAP:Class>
    <MAP:RDBSchema>product</MAP:RDBSchema>
    <MAP:Map>
    	<MAP:Property name="id" type="int" colName="id" primary-key="true"/>
    	<MAP:Property name="name" type="string" colName="name"/>
    	<MAP:Property name="catId" type="long" colName="cat_id"/> 	
    	<MAP:one-2-one name="details" ref-class="com.sales.pojo.ProductDetails" foreign-key="ID"/>
    	<MAP:one-2-one name="stock" ref-class="com.sales.pojo.Stock" foreign-key="ID"/>
    	<MAP:one-2-one name="epd" ref-class="com.sales.pojo.ElectronicProductDetails" foreign-key="ID"/>
    	<MAP:one-2-many ref-class="com.sales.pojo.Stock" name="stocks" foreign-key="ID" collectionType="list"/>
    </MAP:Map>
  </MAP:Mapping>
  
  <MAP:Mapping>
  	<MAP:Class>com.sales.pojo.ProductDetails</MAP:Class>
  	<MAP:RDBSchema>product_details</MAP:RDBSchema>
  	<MAP:Map>
     	<MAP:Property name="id" type="int" colName="id" primary-key="true"/>
  		<MAP:Property name="prodId" type="int" colName="PROD_ID"/>
  		<MAP:Property name="brand" type="string" colName="BRAND"/>
  		<MAP:Property name="color" type="string" colName="COLOR"/>
  		<MAP:Property name="productSize" type="string" colName="PROD_SIZE"/>
  		<MAP:Property name="price" type="int" colName="PRICE"/>
  		<MAP:Property name="material" type="string" colName="MATERIAL"/>
  		<MAP:one-2-one name="product" ref-class="com.sales.pojo.Prodcty" foreign-key="PROD_ID"/>
  	</MAP:Map>
  </MAP:Mapping>
  <MAP:Mapping>
  	<MAP:Class>com.sales.pojo.ElectronicProductDetails</MAP:Class>
  	<MAP:RDBSchema>ELECTRONIC_PRODUCT_DETAILS</MAP:RDBSchema>
  	<MAP:Map>
     	<MAP:Property name="id" type="int" colName="id" primary-key="true"/>
  		<MAP:Property name="description" type="string" colName="ELE_DESCRIPTION"/>
  		<MAP:Property name="techDetails" type="string" colName="TECH_DETAILS"/>
  		<MAP:Property name="prodId" type="int" colName="PROD_ID"/>
  		<MAP:Property name="brand" type="string" colName="BRAND"/>
  		<MAP:Property name="color" type="string" colName="COLOR"/>
  		<MAP:Property name="price" type="int" colName="PRICE"/>
  		<MAP:Property name="material" type="string" colName="MATERIAL"/>
  		<MAP:one-2-one name="product" ref-class="com.sales.pojo.Prodcty" foreign-key="PROD_ID"/>
  		<!--<MAP:one-2-one name="" ref-class="com.sales.pojo.Prodcty" foreign-key="id"/>
  	--></MAP:Map>
  </MAP:Mapping>
  
</MAP:Mappings>
